### PR TITLE
Fixed disabled displays causing detection issues

### PR DESCRIPTION
**Pull request by xanderfrangos**
Disabling a monitor in Windows can cause the monitor scanning to stop working. I haphazardly fixed it. I'm not sure that this doesn't cause bugs elsewhere, but I've been using it in a real app and nobody has reported issues.

### CODE REVIEW

**Comment by xanderfrangos** [comment]
It's all to address bugs when displays are disabled (or "disconnected") in Windows. Like I said, it was a bit of a haphazard fix. I'm not entirely sure why it worked. Your original code works fine if no monitors are disabled in Windows. I required additional flags to be enabled ("Attached to desktop" and "Active") to avoid disabled displays from being considered valid displays. 

The larger fixes were the adjustment to the loop and always working with physical monitor 0. The loop seemed to cut off one short, and disabled displays go to the start of the list. So one real display would get cut off at the end. As for forcing "physicalMonitor[0]"... I have no clue why that works. All active displays seemed to be mapped to that and not the index that's being looped through. But your original code works for configurations with 0 disabled displays, so I don't know how to explain the odd behavior.

**Comment by hensm** [comment]
Okay, I’ll do some testing.

As far as I remember, an HMONITOR handle will have multiple physical monitors if, for example, you configure a secondary display to duplicate, instead of extend. This likely applies to virtual monitors created by something like Eyefinity or NVIDIA Surround, too. Not sure what’s happening there with disabled displays, though.

**Comment by hensm** [comment]
Can you report back the output of this?

EXE: [ConsoleApplication1.zip](https://github.com/hensm/node-ddcci/files/4484946/ConsoleApplication1.zip)
Source: [ConsoleApplication1Source.zip](https://github.com/hensm/node-ddcci/files/4484951/ConsoleApplication1Source.zip)

**Comment by xanderfrangos** [comment]
[one-display-off.txt](https://github.com/hensm/node-ddcci/files/4487207/one-display-off.txt)
[all-displays-on.txt](https://github.com/hensm/node-ddcci/files/4487208/all-displays-on.txt)

I ran it twice: once with all 4 displays on, once with 3 out of 4 on.

**Comment by hensm** [comment]
Looks like one of the monitors gets pushed to a higher index, which would explain why extending the loop bounds "fixes" it, but it should still show up when querying the physical monitor count that sets the loop bounds in the first place, so I'm a little stumped.

Try this one, it's probably very verbose:
[ConsoleApplication1.zip](https://github.com/hensm/node-ddcci/files/4487925/ConsoleApplication1.zip)

**Comment by xanderfrangos** [comment]
[all-displays-on_2.txt](https://github.com/hensm/node-ddcci/files/4488013/all-displays-on_2.txt)
[one-display-off_2.txt](https://github.com/hensm/node-ddcci/files/4488014/one-display-off_2.txt)

**Comment by hensm** [comment]
Seems like it worked fine that time, but I didn't change anything consequential. Not sure what to do now.

I guess just try this and if it still has problems, I'll merge this PR and call it a day:
https://github.com/hensm/node-ddcci/tree/testing

**Comment by xanderfrangos** [comment]
The testing branch seems to detect everything OK in my app. I'll do more testing later and let you know.

**Comment by xanderfrangos** [comment]
Actually, the new branch may not be better. Now I'm not able to reproduce the issue with the old code (or your first EXE). WTF Windows?

**Comment by xanderfrangos** [comment]
Okay, I was able to reproduce it again after switching different displays off. The testing branch does not fix the issue. 

Here's the output from your 2nd EXE:
[two-displays-off.txt](https://github.com/hensm/node-ddcci/files/4489004/two-displays-off.txt)

I also had a chance to test with my app. The old code and your testing branch do not find any displays in my current display configuration (2 off, 2 on). Meanwhile, the code from is PR does correctly detect them.

I get the feeling that this is a Windows bug and that node-ddcci is doing everything correctly.

**Comment by hensm** [comment]
> I get the feeling that this is a Windows bug and not actually something wrong with the module.

I'm thinking that, too. Maybe a monitor firmware bug causing issues? Debugging Windows code is not my area of expertise, that's for sure.

Also, looking at the PR changes again, the problem is that it will break when there really are multiple physical monitors, since you only take the first one.

**Comment by xanderfrangos** [comment]
According to the output from your EXEs, hard coding physicalMonitor[0] doesn't actually seem to be doing anything. It never goes beyond 1. So that change may have been frivolous.

**Comment by hensm** [comment]
Working theory is that the monitor index is bumped `\\.\DISPLAY1\Monitor0` -> `\\.\DISPLAY1\Monitor1`, but without a corresponding change to whatever `GetNumberOfPhysicalMonitorsFromHMONITOR` returns, so when you extend the loop for an extra iteration, the name matches up since you only removed one use of `i`, but you don't access invalid memory because you always take the first monitor.

So, both changes work together.

Could be completely wrong, but that's what makes sense to me right now.

**Comment by xanderfrangos** [comment]
Any idea of what `physicalMonitor[1]` or higher would be? Daisy-chaining? Multiple panels in one monitor (like some 4k/5k displays with 2 HDMI ports)?

EDIT: Looks like it's related to mirroring.
EDIT 2: With my PR, it correctly finds all displays in a mirrored configuration, but sends both VCP codes to the same physical monitor. So I guess I found the side-effect of hard-coding `physicalMonitor[0]`.
EDIT 3: After further testing I've found that `physicalMonitor[i]` fixes mirrored displays but (sometimes) breaks detection when displays are disabled, while hard-coding `physicalMonitor[0]` breaks brightness updates to mirrored displays but fixes the disabled displays bug. Any ideas on how to get both to work?

**Comment by xanderfrangos** [comment]
Added a fix for the mirrored display issue.

**Comment by hensm** [comment]
Pretty late here now, will take a look tomorrow.

**Comment by hensm** [comment]
Okay, still can't say I understand exactly what's going on, but if it works, it works. Just rebase against the refactored version and I'll merge and push an NPM update. Physical monitor loop is outside of `EnumDisplayDevices` loops now.

**Comment by xanderfrangos** [comment]
Okay, it's updated for the refactor. Just going to test it out a little more to make sure there's no new bugs.

EDIT: Found a mirroring bug that doesn't occur in the pre-rebase version. Should be able to fix it in a few hours.

**Comment by xanderfrangos** [comment]
Okay, the latest commit looks good to go. No amount of disabling or mirroring (or mirroring AND disabling) breaks it.

**Comment by hensm** [comment]
Published v0.0.4

**Pull request merged**
